### ISSUE TITLE
Goke GK7202V300_S38

### ISSUE THREAD

**Issue by chross** [OpenIPC/coupler#23]
Hi!
Do you have any plans on releasing a version for the Goke GK7202V300_S38 cam?
I have the following information, if that helps:
Platform:
G2-EA_GK7202V300_S38
System version:
V1.01.LITEOS.000729M5.00000.030007.00000

Kind regards

**Comment by widgetii** [comment]
It's some kind of RTOS on the board (LiteOS), not even a Linux
